# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(800, 600)
        Menu.setMinimumSize(QtCore.QSize(800, 600))
        Menu.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Img/reveja (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Menu.setWindowIcon(icon)
        Menu.setStyleSheet("background-color: rgb(61, 61, 61);")
        self.centralwidget = QtWidgets.QWidget(Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.main_txt = QtWidgets.QLabel(self.centralwidget)
        self.main_txt.setGeometry(QtCore.QRect(80, -10, 661, 151))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.main_txt.setFont(font)
        self.main_txt.setStyleSheet("color: rgb(255, 255, 255);")
        self.main_txt.setObjectName("main_txt")
        self.avaliation_btn = QtWidgets.QPushButton(self.centralwidget)
        self.avaliation_btn.setGeometry(QtCore.QRect(290, 160, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.avaliation_btn.setFont(font)
        self.avaliation_btn.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.avaliation_btn.setObjectName("avaliation_btn")
        self.view_avaliation_btn = QtWidgets.QPushButton(self.centralwidget)
        self.view_avaliation_btn.setGeometry(QtCore.QRect(290, 250, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.view_avaliation_btn.setFont(font)
        self.view_avaliation_btn.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.view_avaliation_btn.setObjectName("view_avaliation_btn")
        Menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        Menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Menu)
        self.statusbar.setObjectName("statusbar")
        Menu.setStatusBar(self.statusbar)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Menu"))
        self.main_txt.setText(_translate("Menu", "MetricsManager"))
        self.avaliation_btn.setText(_translate("Menu", "Deixar Avaliação (Usuário)"))
        self.view_avaliation_btn.setText(_translate("Menu", "Visualizar Avaliações (Admin)"))
import imgs_rc
