# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualize.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from utils.view_archive import open_archive, is_file_open
import os

class Ui_Visualizar(object):
    def back_to_menu(self):
        from .main_menu import Ui_Menu 
        self.menu = QtWidgets.QMainWindow()
        self.ui = Ui_Menu()
        self.ui.setupUi(self.menu)
        self.menu.show()

    def warning_archive_open(self):
        msg = QtWidgets.QMessageBox()
        msg.setText("Não existem registros desse tipo de avaliação")
        msg.exec_()

    def try_open_archive(self, archive_name):
        if os.path.exists(archive_name):
            os.system(f"start notepad {archive_name}")
        else:
            self.warning_archive_open()

    def setupUi(self, Visualizar):
        Visualizar.setObjectName("Visualizar")
        Visualizar.resize(829, 712)
        Visualizar.setMaximumSize(QtCore.QSize(829, 712))
        font = QtGui.QFont()
        font.setPointSize(2)
        Visualizar.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("screens/reveja (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Visualizar.setWindowIcon(icon)
        Visualizar.setStyleSheet("background-color: rgb(61, 61, 61);\n"
"")
        self.centralwidget = QtWidgets.QWidget(Visualizar)
        self.centralwidget.setMinimumSize(QtCore.QSize(829, 686))
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 230, 151, 111))
        self.label.setStyleSheet("image: url(screens/voto-positivo.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.main_txt_2 = QtWidgets.QLabel(self.centralwidget)
        self.main_txt_2.setGeometry(QtCore.QRect(80, 10, 651, 111))
        self.main_txt_2.setMinimumSize(QtCore.QSize(651, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.main_txt_2.setFont(font)
        self.main_txt_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.main_txt_2.setObjectName("main_txt_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 230, 151, 111))
        self.label_2.setStyleSheet("image: url(screens/voto-negativo.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(590, 230, 151, 111))
        self.label_4.setStyleSheet("image: url('screens/ruim.png');")
        self.label_4.setText("")
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.view_positives_btn = QtWidgets.QPushButton(self.centralwidget)
        self.view_positives_btn.setGeometry(QtCore.QRect(80, 360, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.view_positives_btn.setFont(font)
        self.view_positives_btn.setStyleSheet("background-color: rgb(117, 112, 214);")
        self.view_positives_btn.setObjectName("view_positives_btn")
        self.view_negatives_btn = QtWidgets.QPushButton(self.centralwidget)
        self.view_negatives_btn.setGeometry(QtCore.QRect(340, 360, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.view_negatives_btn.setFont(font)
        self.view_negatives_btn.setStyleSheet("background-color: rgb(245, 140, 121);")
        self.view_negatives_btn.setObjectName("view_negatives_btn")
        self.view_inapropriates_btn = QtWidgets.QPushButton(self.centralwidget)
        self.view_inapropriates_btn.setGeometry(QtCore.QRect(600, 360, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.view_inapropriates_btn.setFont(font)
        self.view_inapropriates_btn.setStyleSheet("background-color: rgb(242, 107, 56);")
        self.view_inapropriates_btn.setObjectName("view_inapropriates_btn")
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(10, 620, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.back_btn.setObjectName("back_btn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 160, 531, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        Visualizar.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Visualizar)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 26))
        self.menubar.setObjectName("menubar")
        Visualizar.setMenuBar(self.menubar)

        self.retranslateUi(Visualizar)
        self.view_positives_btn.clicked.connect(lambda: self.try_open_archive("avaliaçoes_positivas.txt"))
        self.view_negatives_btn.clicked.connect(lambda: self.try_open_archive("avaliaçoes_negativas.txt"))
        self.view_inapropriates_btn.clicked.connect(lambda: self.try_open_archive("avaliaçoes_impróprias.txt"))
        self.back_btn.clicked.connect(self.back_to_menu)
        self.back_btn.clicked.connect(Visualizar.close)
        QtCore.QMetaObject.connectSlotsByName(Visualizar)

    def retranslateUi(self, Visualizar):
        _translate = QtCore.QCoreApplication.translate
        Visualizar.setWindowTitle(_translate("Visualizar", "Visualizar"))
        self.main_txt_2.setText(_translate("Visualizar", "MetricsManager"))
        self.view_positives_btn.setText(_translate("Visualizar", "Avaliações Positivas"))
        self.view_negatives_btn.setText(_translate("Visualizar", "Avaliações Negativas"))
        self.view_inapropriates_btn.setText(_translate("Visualizar", "Avaliações Impróprias"))
        self.back_btn.setText(_translate("Visualizar", "Voltar"))
        self.label_3.setText(_translate("Visualizar", "Selecione o tipo de avaliação que deseja visualizar:"))
